export const KIBBE_BOOK_CHUNKS: string[] = [
  // General Type Descriptions
  "Dramatic (D): Dramatic vücut tipi, uzun, keskin ve köşeli bir kemik yapısıyla karakterize edilir. Dikey olarak, gerçek boylarından bağımsız olarak çok uzun görünürler. Omuzlar genellikle dar ve keskindi. İdeal kilolarında vücut etleri genellikle gergin ve kaslıdır. Yüz kemikleri keskin ve belirgindir - keskin bir çene hattı, yüksek elmacık kemikleri ve belirgin bir burun yaygındır. Genel izlenim cesur, asil ve karizmatiktir. Dramatic'ler için stil önerileri, keskin dikey çizgilerini onurlandırmaya odaklanır. Uzun, kesintisiz silüetler, keskin terzilik ve cesur, geometrik şekillerle en iyi görünürler. Ağır, büyük boyutlu kumaşlar ve minimalist, heykelsi aksesuarlar iyi çalışır.",
  "Romantic (R): Romantic vücut tipi, Yin'in özüdür. Yumuşak, yuvarlak şekiller ve dolgun, şehvetli bir vücut ile tanımlanır. Kemik yapısı narin ve küçüktür, genellikle daha kısa bir dikey çizgiye sahiptir. Omuzlar eğimli ve yuvarlaktır. Romantic'ler, kıvrımlı bir göğüs ve kalça ile ince bir bele sahip belirgin bir kum saati figürüne sahiptir. Yüz özellikleri de yumuşak ve dolgundur: büyük, yuvarlak gözler, dolgun dudaklar ve yumuşak yanaklar. Genel izlenim şehvetli, göz alıcı ve çekicidir. Romantic'ler için stil önerileri, kıvrımlarını ve yumuşaklıklarını vurgulamalıdır. Dökümlü kumaşlar, bel vurgusu, süslü detaylar ve giysi ve aksesuarlarda yumuşak, yuvarlak şekiller anahtardır. Çok sert, düz veya geometrik her şeyden kaçınmalıdırlar.",
  "Classic (C): Classic vücut tipi, Yin ve Yang'ın mükemmel bir karışımıdır ve dengeli, simetrik ve ölçülü bir fizik ile sonuçlanır. Classic'te hiçbir şey aşırı değildir. Orta bir dikey çizgileri, eşit orantılı omuzları, belleri ve kalçaları vardır. Kemik yapıları ne keskin ne de yuvarlaktır, ancak simetrik ve sivrilendir. Yüz özellikleri de düzenli ve eşit aralıklıdır. Genel izlenim rafine, zarif ve zamansızdır. Classic'ler için stil önerileri, doğal simetrilerini yansıtmalıdır. Temiz, basit çizgiler, pürüzsüz, akıcı silüetler ve yüksek kaliteli, basit kumaşlar idealdir. Aşırı süslü, telaşlı veya büyük boyutlu her şeyden kaçınmalıdırlar, çünkü bu dengeli yapılarını kolayca bastırabilir. Zamansız ve zarif parçalar, bir Classic'in gardırobunun temelini oluşturur.",
  "Natural (N): Natural vücut tipi, geniş ve köşeli olan ancak bir Dramatic kadar keskin veya dar olmayan, Yang-baskın bir kemik yapısına sahiptir. Orta ila uzun bir dikey çizgileri ve genellikle geniş omuzları vardır. Vücut şekilleri genellikle düzdür ve kaslı olma eğilimindedir. Yüz kemikleri de geniş ve hafif köşelidir, ancak keskin değildir. Genel izlenim taze, ulaşılabilir ve atletiktir. Natural'lar için stil önerileri, rahat silüetlere ve doğal, dokulu kumaşlara odaklanır. Yapılandırılmamış ceketler, rahat trikolar ve düz paça pantolonlar mükemmel seçimlerdir. Aşırı kısıtlayıcı veya süslü giysilerden kaçınmalıdırlar. Toprak tonları ve el yapımı aksesuarlar, rahat havalarını tamamlar.",
  "Gamine (G): Gamine vücut tipi, zıtlıkların eşsiz bir birleşimidir; keskin Yang ve yumuşak Yin'in eşit ölçüde, ancak küçük bir ölçekte bir karışımıdır. Minyon ve narin bir iskeletleri vardır, ancak kemik yapıları keskin ve köşelidir. Genellikle erkeksi veya peri gibi bir çekicilikleri vardır. Gamine'ler kısa olma eğilimindedir, doğal olarak düz ve dar bir vücut şekline sahiptirler. Yüz özellikleri de bir karışımdır: büyük, bebek gibi gözler (Yin), keskin, sivrilen bir çene (Yang) ile eşleşebilir. Genel izlenim enerjik, eğlenceli ve şıktır. Gamine'ler için stil önerileri, silüeti renk bloklama, kısa boylar ve keskin, geometrik detaylarla kırmayı içerir. Dokuların ve desenlerin eğlenceli bir karışımı son derece iyi çalışır. Uzun, kesintisiz çizgilerden ve monokromatik görünümlerden kaçınmalıdırlar.",

  // Subtype Descriptions
  "Soft Gamine (SG): Soft Gamine, bir Gamine'in üzerine bir tutam Yin eklenmiş halidir. Gamine'in zıtlıkların birleşimine (keskin ve yuvarlak) sahiptirler, ancak vücut etlerinde ve yüz özelliklerinde daha fazla yumuşaklık vardır. Narin, hafif geniş kemiklere sahip minyonlardır. Vücut şekilleri kıvrımlı ve bebek gibidir, belirgin bir bele sahiptirler. Yüz özellikleri dolgun ve yuvarlaktır, genellikle büyük gözler ve dolgun yanaklar bulunur. Stil önerileri arasında keskin, yuvarlak şekiller, detaylarda animasyon ve bolca bel vurgusu bulunur. Karmaşık detaylara sahip ayrı parçalar ve dokuların eğlenceli bir karışımı iyi çalışır.",
  "Flamboyant Natural (FN): Flamboyant Natural, Dramatic ailesinden eklenmiş keskinlik ve uzunluğa sahip bir Natural'dır. Geniş, köşeli bir iskelete sahip uzun boyludurlar. Belirleyici özellikleri, uzun bir dikey çizgi ile birleşen omuzlardaki genişliktir. Geleneksel bir kum saati anlamında kıvrımlı değillerdir, ancak güçlü, atletik bir yapıları vardır. Stil önerileri, güçlü omuzlarını vurgulayan bir 'T' siluetine odaklanır. Yapılandırılmamış, büyük boyutlu ve akıcı parçalar onlara harika görünür. Cesur dokuları, büyük ölçekli desenleri ve kalın aksesuarları kolaylıkla taşıyabilirler.",

  // Wardrobe Essentials (Organized)
  "Dramatic (D) Gardırop Temelleri: Dramatic'in gardırobu, keskin dikey çizgilerini vurgulayan parçalardan oluşmalıdır. Olmazsa olmazlar arasında; omuzları belirgin, uzun ve tek düğmeli blazer ceketler, dikey çizgili veya tek renkli ipek gömlekler, dar ve düz kesim kumaş pantolonlar, yere kadar uzanan maksi elbiseler ve etekler bulunur. Aksesuar olarak, büyük, geometrik ve heykelsi takılar (uzun kolyeler, keskin küpeler) ve sivri burunlu ayakkabılar tercih edilmelidir.",
  "Soft Dramatic (SD) Gardırop Temelleri: Soft Dramatic, Dramatic'in cesur dikeyini Romantic'in şehvetli kıvrımlarıyla birleştirir. Gardırop, büyük ölçekli ve cesur olmalı, ancak aynı zamanda vücudu sarmalı ve dökümlü olmalıdır. Temel parçalar; büyük yakalı veya drapeli detaylı, uzun ve omuzları belirgin ceketler, yumuşak ve parlak kumaşlardan yapılmış (ipek, saten) dökümlü bluzlar, yüksek belli ve geniş paçalı pantolonlar ve vücudu saran maksi elbiselerdir. Aksesuarlar büyük, gösterişli ve yuvarlak hatlara sahip olmalıdır. Büyük kolyeler, gösterişli küpeler ve yumuşak deri çantalar idealdir.",
  "Romantic (R) Gardırop Temelleri: Romantic gardırobu, yumuşaklığı ve kıvrımları kutlamalıdır. Temel parçalar; beli vurgulayan dökümlü kumaşlardan elbiseler, yuvarlak yakalı veya fırfırlı detaylara sahip yumuşak bluzlar, yüksek belli kalem etekler ve yumuşak dokulu kazaklardır. İnce ve zarif takılar, yuvarlak burunlu ayakkabılar ve küçük, yuvarlak çantalar bu stili tamamlar. Kumaş olarak ipek, şifon ve ince trikolar idealdir.",
  "Theatrical Romantic (TR) Gardırop Temelleri: Theatrical Romantic, Romantic'in yumuşaklığına Dramatic'in keskin bir dokunuşunu ekler. Gardıropta; omuzları süslü veya vatkalı bluzlar, peplum detaylı üstler, dar kesim kadife veya ipek pantolonlar, vücudu saran ve dökümlü kumaşlardan yapılmış elbiseler bulunmalıdır. Aksesuarlar gösterişli ve parlak olmalıdır; büyük taşlı kolyeler, parıltılı küpeler ve zarif, süslü topuklu ayakkabılar stili tamamlar.",
  "Classic (C) Gardırop Temelleri: Classic gardırobu zamansız, zarif ve dengeli olmalıdır. Her Classic'in dolabında olması gerekenler; kaliteli bir trençkot veya sade bir palto, tam oturan beyaz gömlekler, düz paça veya hafif boru paça pantolonlar, sade kılıf elbiseler (sheath dress) ve kaliteli bir blazer cekettir. Aksesuarlar minimalist olmalıdır; inci küpeler, ince bir zincir kolye, klasik bir saat ve yapılı bir deri çanta mükemmel seçimlerdir.",
  "Dramatic Classic (DC) Gardırop Temelleri: Dramatic Classic, Classic'in dengeli yapısına Dramatic'in keskinliğini ekler. Gardırop, sade, zarif ama aynı zamanda keskin ve yapılandırılmış olmalıdır. Olmazsa olmazlar; keskin omuzlu ve tam oturan blazer ceketler, V yakalı veya geometrik desenli kaliteli gömlekler, ütü çizgili kumaş pantolonlar ve keskin hatlı kılıf elbiselerdir. Kumaşlar orta ağırlıkta ve pürüzsüz olmalıdır. Aksesuarlar zarif, geometrik ve minimalist olmalıdır. Kaliteli bir deri çanta, sivri burunlu ayakkabılar ve sade, modern takılar bu stili tamamlar.",
  "Soft Classic (SC) Gardırop Temelleri: Soft Classic, Classic'in dengesine Romantic'in yumuşaklığını katar. Gardırop; yumuşak kumaşlardan yapılmış, beli hafifçe belli eden blazer ceketler, dökümlü ve sade bluzlar, hafifçe bollaşan kumaş pantolonlar ve diz hizasında biten hafif A-kesim eteklerden oluşmalıdır. Aksesuarlar zarif, simetrik ve hafifçe süslü olabilir. İnce kolyeler ve küçük, zarif küpeler idealdir.",
  "Natural (N) Gardırop Temelleri: Natural gardırobu rahat, dokulu ve bohem bir havaya sahip olmalıdır. Temel parçalar; rahat kesim kot pantolonlar (boyfriend veya straight-leg), dokulu ve salaş kazaklar, keten veya pamuklu gömlekler, yapılandırılmamış ve cepsiz blazer ceketler ve sade maksi elbiselerdir. Aksesuar olarak, el yapımı görünümlü takılar, büyük deri çantalar, süet botlar ve düz sandaletler bu doğal stili tamamlar.",
  "Flamboyant Natural (FN) Gardırop Temelleri: Flamboyant Natural, rahatlığı ve cesur çizgileri bir araya getirmelidir. Gardırobun olmazsa olmazları arasında; uzun, açık ve dökümlü hırkalar, büyük boy ve salaş kazaklar, geniş paça veya bol kesim pantolonlar, omuzları açıkta bırakan üstler (off-the-shoulder), ve basit, dökümlü tişörtler bulunur. Aksesuarlar büyük, cesur ve etnik desenli olabilir. Büyük ve katmanlı kolyeler, geniş bilezikler ve büyük çantalar bu görünümü mükemmel şekilde tamamlar.",
  "Soft Natural (SN) Gardırop Temelleri: Soft Natural, Natural'ın rahatlığına Romantic'in yumuşak kıvrımlarını ekler. Gardırop, rahat, akıcı ve beli hafifçe vurgulayan parçalardan oluşmalıdır. Temel parçalar arasında; bele oturan yumuşak hırkalar ve ceketler, dökümlü ve asimetrik kesimli bluzlar, yumuşak kumaşlardan yapılmış yüksek belli pantolonlar ve beli kemerle vurgulanmış elbiseler bulunur. Kumaşlar hafif dokulu ve akıcı olmalıdır. Aksesuarlar doğal malzemelerden yapılmış, orta büyüklükte ve hafifçe yuvarlak hatlara sahip olmalıdır. El yapımı takılar ve rahat çantalar stili tamamlar.",
  "Gamine (G) Gardırop Temelleri: Gamine gardırobu enerjik, eğlenceli ve zıtlıklarla dolu olmalıdır. Kısa kesim (cropped) ceketler ve hırkalar, yüksek belli dar pantolonlar (skinny veya slim-fit), eğlenceli desenlere sahip bluzlar, A-kesim mini etekler ve ilginç tasarımlı düz ayakkabılar (oxford, loafer) gardırobun temelini oluşturur. Renk bloklama ve farklı dokuları bir arada kullanmak Gamine stili için anahtardır.",
  "Flamboyant Gamine (FG) Gardırop Temelleri: Flamboyant Gamine, Gamine'in zıtlıklarına Dramatic'in keskin ve uzun hatlarını ekler. Gardırop, asimetrik, geometrik ve bol renkli parçalarla dolu olmalıdır. Temel parçalar; keskin yakalı ve kısa kesim (cropped) ceketler, cesur desenli veya renk bloklu üstler, dar ve bilekte biten pantolonlar (cropped pants) ve asimetrik kesimli etekler veya elbiselerdir. Kumaşlar sert ve şeklini koruyan türden olabilir. Aksesuarlar eğlenceli, büyük ve geometrik şekillerde olmalıdır. Büyük küpeler, ilginç tasarımlı çantalar ve renkli ayakkabılar bu enerjik stili vurgular.",
  "Soft Gamine (SG) Gardırop Temelleri: Soft Gamine, Romantic ve Gamine'in bir karışımıdır ve gardıropları bu zıtlığı yansıtmalıdır. Beli vurgulayan kısa ceketler, yuvarlak yakalı ve fırfırlı detaylara sahip bluzlar, yüksek belli ve bilekte biten pantolonlar ve eğlenceli desenlere sahip elbiseler harika seçimlerdir. Aksesuarlar küçük, ilginç ve yuvarlak hatlara sahip olmalıdır. Renkli babetler ve küçük, dikkat çekici çantalar bu stili tamamlar.",

  // Fashion Dictionary
  "Moda Sözlüğü (Silüet): Silüet, bir giysinin vücut üzerinde oluşturduğu dış hattır. Vücut tipinize uygun silüeti seçmek, dengeli bir görünüm yaratmanın anahtarıdır. Yaygın silüet türleri arasında 'A-kesim' (belden aşağı doğru genişleyen), 'Kalem' (vücudu saran, dar kesim), 'İmparatorluk' (göğüs altından bollaşan) ve 'Balo Elbisesi' (dar üst ve çok kabarık etek) bulunur.",
  "Moda Sözlüğü (Kumaş Türleri): Kumaşlar, bir giysinin nasıl durduğunu, dökümünü ve hissini belirler. Doğal kumaşlar (pamuk, keten, ipek, yün) genellikle nefes alabilir ve rahattır. Sentetik kumaşlar (polyester, naylon, rayon) ise daha dayanıklı olabilir ve daha az kırışır. Kumaşın dokusu (pürüzsüz, pürüzlü, parlak, mat) ve ağırlığı da stilinizde önemli bir rol oynar.",
  "Moda Sözlüğü (Renk Paleti): Renk paleti, bir gardıropta veya kombinde kullanılan uyumlu renkler grubudur. Kişisel renk paletinizi oluşturmak, cilt alt tonunuza (sıcak, soğuk veya nötr) uygun renkleri bulmayı içerir. Genellikle bir renk paleti, 'nötr' ana renklerden (siyah, beyaz, bej, gri), birkaç ana renkten ve kombinlere canlılık katmak için kullanılan 'vurgu' renklerinden oluşur.",
  "Moda Sözlüğü (Akım Kesimler/Trendler): Akım kesimler, belirli bir sezonda veya dönemde popüler olan giysi stillerini ifade eder. Örneğin, 'yüksek bel' pantolonlar, 'oversize' (bol kesim) ceketler veya 'crop top' (kısa üstler) belirli dönemlerde popüler olan akım kesimlerdir. Trendleri takip etmek eğlenceli olsa da, stilinizi oluştururken vücut tipinize ve kişisel zevkinize uygun, zamansız parçalara yatırım yapmak daha sürdürülebilir bir yaklaşımdır."
];
